---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'create and access variables inside the playbook'

  # Target: where our play will run and options it will run with
  hosts: ansnode1
  gather_facts: false

  # Variable: variables that will apply to the play, on all target systems
  vars_prompt:
    - name: username
      private: false
  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Displaying vars_prompt value of name
       debug:
         msg: "{{ username }}"
# Three dots indicate the end of a YAML document
...
