---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'create and access variables inside the playbook'

  # Target: where our play will run and options it will run with
  hosts: webservers
  gather_facts: false

  # Variable: variables that will apply to the play, on all target systems
  vars:
    dict:
      dict_key: This is a dictionary variable value
  
  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Displaying named dictionary dictionary
       debug:
         msg: "{{ dict }}"
     - name: Displaying name dictionary dictionary key value with dictionary dot notation
       debug:
         msg:  "{{ dict.dict_key }}"
     - name: Displaying named dictionary dictionary key value with python backets notation
       debug: "{{ dict['dict_key']}}"

# Three dots indicate the end of a YAML document
...
