---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'create and access variables inside the playbook'

  # Target: where our play will run and options it will run with
  hosts: ansnodes
  gather_facts: true

 
  # Task: the list of tasks that will be executed within the playbook
  tasks:       
     - name: Displaying hostvars with an ansible fact and collect ansible port value with dot notation
       debug:
         msg: "{{ hostvars[ansible_hostname].ansible_port | default('') }}"
     - name: Displaying hostvars with an ansible fact and collect ansible port with dict notation
       debug:
         msg: "{{ hostvars[ansible_hostname]['ansible_port'] | default('') }}"
# Three dots indicate the end of a YAML document
...
